name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish NuGet Package
    env:
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          source-url: https://nuget.pkg.github.com/jasonlandbridge/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Create the package
        run: dotnet pack --configuration Release ./PlexAPI/PlexAPI.csproj

      - name: Publish the package to nuget.org
        run: dotnet nuget push ./PlexAPI/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
